#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

[default_session]
preview_command = "eza --tree --color=always --icons --all {}"

[[session]]
name = "Downloads"
path = "~/Downloads"

[[session]]
name = "dotfiles"
path = "~/dotfiles"

[[session]]
name = "Notes"
path = "~/notes"

[[session]]
name = "Music"
path = "~/Music"
startup_command = "rmpc"

[[session]]
name = "Documents"
path = "~/Documents"

[[session]]
name = "Projects"
path = "~/github"

[[session]]
name = "Home"
path = "~"
