"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
show_hidden = true
show_symlink = true
title_format = "Yazi"
ratio = [1, 3, 3]

[plugin]

prepend_fetchers = [
    # Git
    { id = "git", url = "*", run = "git" },
    { id = "git", url = "*/", run = "git" },
]

prepend_previewers = [
    { url = "*.typ", run = 'piper -- bat -p --color=always "$1"' },
    { url = "*.mp3", run = 'piper -- unbuffer eyed3 "$1"' },
]

[opener]
play = [{ run = 'iina --no-stdin "$@"' }]

[open]
prepend_rules = [{ mime = "video/*", use = "play" }]

[preview]
max_width = 5000
max_height = 7500
